name: Deploy and Trigger DAG on Cloud Composer
 
on:
  push:
    branches:
      - main
 
jobs:
  deploy_and_trigger:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
 
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
          project_id: tidy-simplicity-442419-q7
          credentials_json: ${{ secrets.GCP_SA_KEY }}
 
    - name: Upload DAG to Composer
      run: |
        gsutil cp dags/trigger_dag.py gs://us-central1-traindag-93ffccec-bucket/dags/trigger_dag.py
        gsutil cp train_and_save_model.py/ gs://us-central1-traindag-93ffccec-bucket/dags/my_operators/train_and_save_model.py/
 
    - name: Trigger the DAG
      run: |
        gcloud composer environments run dagtrigger \
          --location=us-central1 trigger_dag \
          -- <DAG_NAME>
